package com.example.dogwalkingapp;


import android.annotation.SuppressLint;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;

import android.os.Build;
import android.os.Bundle;
import android.os.IBinder;
import android.text.format.Time;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.RequiresApi;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * TrackingService class creates the service that broadcasts the user's gps information that is received by the WalkTracking class to be used
 * for tracking the user's current location as well as the start and end times of the tracking service
 */
public class TrackingService extends Service {
    /**
     * Creates variables for storing the current and previous locations being generated by the tracking service
     */
    private Location PreviousLocation, CurrentLocation;
    /**
     * Creates the location listener that is used to generate the user's current location
     */
    private LocationListener listener;
    /**
     * Creates the location manager that is used to manage the location listener
     */
    private LocationManager locationManager;
    /**
     * Creates the variable for storing the distance traveled during the tracking service
     */
    private double distanceTraveled;
    /**
     * Creates the variables for storing the starting and ending times for the tracking service
     */
    private Long walkStartTime, walkEndTime;

    /**
     * Overrides the binder method of the service class TrackingService
     * @param intent
     * @return
     */
    @Override
    public IBinder onBind(Intent intent) {
        // TODO: Return the communication channel to the service.
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * Overrides the onCreate method of the service class TrackingService
     * This override creates the GPS listener as well as the broadcast being received by the WalkTracking class
     */
    @SuppressLint("MissingPermission")
    @Override
    public void onCreate() {
        Toast.makeText(this, "Tracking Started", Toast.LENGTH_SHORT).show();
        listener = new LocationListener() {

            Intent i = new Intent("GPS_UPDATE");
            Bundle extras = new Bundle();
            //Generates new gps data each time the location changes
            @Override
            public void onLocationChanged(@NonNull Location location) {
                CurrentLocation = location;
                if (walkStartTime == null) {
                    walkStartTime = CurrentLocation.getTime();
                    extras.putLong("walkStartTime", walkStartTime);
                }
                if (PreviousLocation == null) {
                    distanceTraveled = 0.0;
                    extras.putDouble("distanceTraveled", distanceTraveled);
                    i.putExtras(extras);
                    sendBroadcast(i);
                } else {
                    distanceTraveled += BigDecimal.valueOf((PreviousLocation.distanceTo(CurrentLocation) * 0.000621371192))
                            .setScale(2, RoundingMode.HALF_UP)
                            .doubleValue();
                    extras.putDouble("distanceTraveled", distanceTraveled);
                    i.putExtras(extras);
                    sendBroadcast(i);
                }
                PreviousLocation = CurrentLocation;
                walkEndTime = CurrentLocation.getTime();
                extras.putLong("walkEndTime", walkEndTime);
            }

            @Override
            public void onStatusChanged(String provider, int status, Bundle extras) {
                Toast.makeText(TrackingService.this, "Tracking Paused", Toast.LENGTH_SHORT).show();
            }

        };

        locationManager = (LocationManager) getApplicationContext().getSystemService(Context.LOCATION_SERVICE);
        locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 500, 0, listener);

    }

    /**
     * Overrides the onStartCommand method of the TrackingService service
     * @param intent
     * @param flags
     * @param startId
     * @return
     */
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {

        return START_NOT_STICKY;
    }

    /**
     * Overrides the onDestroy method of the TrackingService service
     */
    @Override
    public void onDestroy() {
        Toast.makeText(this, "Tracking Stopped", Toast.LENGTH_SHORT).show();

        locationManager.removeUpdates(listener);

    }

}